### GENERAL SETTINGS ###

# Site settings
title: Robot Milk Intergalactic
description: "Animation and stuff by Mattis Johansson."
analytics: UA-71940621-1
baseurl: "" #important: start with /
url: "http://robotmilk.co"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
paginate: 8

colors:  #in hex code if not noted else

  primary: "#9b7db4"
  primary_rgb: "0,179,254" #"155,125,180" #rgb of the primary. Needed in some places for rgba.  
  primary_dark: "#111"
  purple: "#9b7db4"
  red: "#FA414B"
  yellowy-white: "#F5EBCD"
  text: "#413c4b" #"#384452" #"#33004D"
  link: "#428bca"

  primary: "#00FA96"
  secondary: "#8264c8"
  dark: "#111"
  link: "#00FA96"
  headline: "#333"
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: vimeo-square
    url: https://vimeo.com/robotmilk
  - title: youtube-play
    url: https://www.youtube.com/channel/UCjADCm_YSFRRX7Zot1Oxj_w
    